### ISSUE TITLE
adatok szemantikus dúsítása

### ISSUE THREAD

**Issue by balintfodor** [DCLab-MediaLab/MediaEval14#9]
Előző alkalommal felmerült a conceptnet5 projekt. http://conceptnet5.media.mit.edu/
1. Utána kell járni, hogy milyen módon tudjuk/célszerű az adatainkat utóbbi projekt felhasználásával dúsítani. Be lehet-e építeni mondjuk Lucene-be, vagy a csv-k feldolgozása után ez egy plusz fázis, vagy egyéb megoldási javaslat ami felmerül.
2. El kell dönteni, hogy a concept5 milyen funkcióit használjuk ki és pontosan hogyan alkalmazzuk az adatainkon.

A döntéseket/javaslatokat/eredményeket le kell írni ennek a feladatnak a comment részébe.

**Comment by sylva1717** [comment]
Itt sajnos a vektortér modell kiépítéséhez szükséges RAM kicsit több, mint ami a gépemben van, a doksi szerint: "At least 10 GB of available RAM, if you are going to run the build_assoc step".

Az API-t mindenesetre kipróbáltam, az egyes szavak simán elérhetőek egy URL-en keresztül, pl. http://conceptnet5.media.mit.edu/data/5.2/c/en/house, ahol megtalálhatóak a különböző kapcsolatok - a house esetében ilyenek mondjuk a house HasA room vagy a home relatedTo house. 

URL-en keresztül ugyanígy beadható még egy csomó más dolog is - még érdekesebb lehet számunkra az asszociációk URL-je: http://conceptnet5.media.mit.edu/data/5.2/assoc/list/en/home .

API doksi itt: https://github.com/commonsense/conceptnet5/wiki/API

**Comment by balintfodor** [comment]
adja, akkor szerintem mehet az api-n keresztül, azzal lesz a legkevesebb bajunk, felveszünk issue-t majd a megbeszélésen

**Comment by realhidden** [comment]
Azureon tudunk sok ramos gépet felhúzni, ha kell.

**Comment by realhidden** [comment]
Véletlen rázártam, sry. :P

**Comment by sylva1717** [comment]
Szerintem próbáljunk API-t előtte, ne szenvedjünk ha nem muszáj :)

----- Pôvodná správa -----
Od: "realhidden" notifications@github.com
Odoslané: ‎3.‎7.‎2014 8:49
Komu: "DCLab-MediaLab/MediaEval14" MediaEval14@noreply.github.com
Kópia: "sylva1717" sylva1717@gmail.com
Predmet: Re: [MediaEval14] adatok szemantikus dúsítása (#9)

Azureon tudunk sok ramos gépet felhúzni, ha kell.
